name: Build documentation
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gen_doc:
    name: Build documentation
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch tags
        if: github.event_name == 'release'
        run: |
          git fetch --tags --force

      - uses: Open-CMSIS-Pack/gen-pack-action@main
        with:
          doxygen-version: 1.9.6
          gen-doc-script: ./Documentation/Doxygen/gen_doc.sh
          doc-path: ./Documentation/html
          gh-pages-branch: gh-pages
